config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'
  
  devise_for :users

  namespace :admin do
    root "application#index"
    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end

    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end      
    end
  end
    
  namespace :api do
    namespace :v1 do
      mount API::V1::Tickets, at: "/projects/:project_id/tickets"
      mount API::V1::Projects, at: "/projects/"
    end

  end
  
  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
  end
  

end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
	before_action :authorize_admin!
	skip_after_action :verify_authorized, :verify_policy_scoped

	def index
	end

	private
	def authorize_admin!
		authenticate_user!
		unless current_user.admin?
			redirect_to root_path, alert: "You need admin access for this."
		end
	end

end

app/controllers/api/v1/application_controller.rb
class API::V1::ApplicationController < Sinatra::Base

private
def set_project
	@project = Project.find(params[:project_id])
end

def set_user
	if env["HTTP_AUTHORIZATION"].present?
		if auth_token = env["HTTP_AUTHORIZATION"].match(/(?<=token=).*/).to_s
			@user = User.find_by!(api_key: auth_token)
			return @user if @user.present?
		end
	end
	unauthenticated!
end

def unauthenticated!
	halt 401, { error: "Unauthenticated" }.to_json
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_action :verify_authorized, except: [:index], unless: :devise_controller?
  after_action :verify_policy_scoped, only: [:index], unless: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  private
  def not_authorized
  	redirect_to root_path, alert: "Not Authorized."
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
	def roles
		roles_hash = {}
		Role.available_roles.each { |role| roles_hash[role.titleize] = role }
		return roles_hash
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(*sections)
		unless sections.empty?
			content_for :title do
				(sections << "Trackr").join(' : ')
			end
		end
	end
	
	def admins_only(&block)
		block.call if current_user.try(:admin?)
	end
end

app/views/admin/application/_form.html.erb
<%= simple_form_for([:admin, project]) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/admin/application/index.html.erb
<div class="row" id="admin">
  <div class="col-md-9">
    <header>
      <h1>Admin Dashboard</h1>
</header>
<p>Welcome</p>
</div>
<div class="col-md-3">
	<h2>Admin Links</h2>
	<ul class="nav nav-stacked">
		<li><%= link_to "Users", admin_users_path %></li>
		<li><%= link_to "States", admin_states_path %></li>
	</ul>
</div>

app/views/admin/application/new.html.erb
<header>
	<h1>New Project</h1>
</header>

<%= render 'form', project: @project %>