config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'
  
  devise_for :users

  namespace :admin do
    root "application#index"
    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end

    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end      
    end
  end
    
  namespace :api do
    namespace :v1 do
      mount API::V1::Tickets, at: "/projects/:project_id/tickets"
      mount API::V1::Projects, at: "/projects/"
    end

  end
  
  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
  end
  

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, presence: true

	has_many :tickets, dependent: :delete_all
	has_many :roles, dependent: :delete_all

	def has_membership?(user)
		roles.exists?(user_id: user)
	end

	[:manager, :editor, :auditor].each do |role|
		define_method "has_#{role}?" do |user|
			roles.exists?(user_id: user, role: role)
		end
	end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		if @project.save
		  redirect_to @project, notice: "Project has been created."
		else
		  flash[:alert] = "Project has not been created."
		  render "new"
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_path, notice: "Project has been deleted."
	end

private
	def project_params
	    params.require(:project).permit(:name, :description)
	end 
end

app/controllers/api/v1/projects.rb
require "sinatra"

module API
	module V1
		class Projects < API::V1::ApplicationController
			before do
				headers "Content-Type" => "text/json"
				set_user
			end

			get "/:id" do
				# params.to_json
				project = Project.find(params[:id])
				unless ProjectPolicy.new(@user, project).show?
					halt 404, "The ticket could not be found."
				end
				ProjectSerializer.new(project).to_json
			end
		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update]

  def index
    @projects = policy_scope(Project)
  end

  def show
    authorize @project, :show?
  end

  def edit
    authorize @project, :update?
  end

  def update
    authorize @project, :update?
    
    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project could not be updated."
      render "edit"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash.alert = "Project not found."
      redirect_to projects_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/projects/edit.html.erb
<header>
	<h1>Editing Project</h1>
</header>

<%= render 'form' %>

app/views/projects/index.html.erb
<header>
  <h1>Listing Projects</h1>

<% admins_only do %>
  <ul class="actions">
    <li><%= link_to "New Project", new_admin_project_path, class: "new-button" %></li> 
  </ul>
<% end %>
</header>
<% @projects.each do |project| %>
<div class="row">
  <div class="col-xs-8 col-md-8">
    <h3><%= link_to project.name, project %></h3>
    <%= project.description %>
  </div>
  <div class="col-xs-12 col-md-4">
    <%= link_to 'Show', project, class: "show-button" %>
    <%= link_to 'Edit', edit_project_path(project), class: "edit-button" %>
    <%= link_to 'Destroy', admin_project_path(project),
          method: :delete, data: { confirm: 'Confirm deletion?' }, class: "delete-button" %>
  </div>
</div>
<hr>
<% end %>

app/views/projects/show.html.erb
<title><%= title(@project.name, "Projects") %></title>

<header>
	<h1><%= @project.name %></h1>

	<p class="lead">
	  <%= @project.description %>
	</p>
	<ul class="actions">
	<% if policy(@project).update? %>
		<li><%= link_to "Edit Project", edit_project_path(@project), class: "edit-button" %></li>
	<% end %>
	<% admins_only do %>
		<li><%= link_to "Delete Project", admin_project_path(@project),
		method: :delete,
		data: { confirm: "Are you sure you want to delete this project?" },
		class: "delete-button" %></li>
	<% end %>
	</ul>
</header>

<header>
	<h2>Tickets</h2>
	<ul class="actions">
	<% if policy(Ticket.new(project: @project)).create? %>
		<li><%= link_to "New Ticket", new_project_ticket_path(@project),
		class: "new-button" %></li>
	<% end %>
	</ul>
</header>

<ul id="tickets">
	<% @project.tickets.each do |ticket| %>
		<li>
			#<%= ticket.id %> -
			<%= link_to ticket.name, [@project, ticket] %>
			<%= render ticket.state if ticket.state %>
			- created on <%= ticket.created_at.to_date %>
		</li>
	<% end %>
</ul>